### ISSUE TITLE
Syslog crash on windows

### ISSUE THREAD

**Issue by Jelle7** [HandsetDetection/python-apikit#18]
Importing syslog on Windows causes a crash in HDBase.py line 25. Could this be removed?

**Comment by elricho** [comment]
Hey Jelle7,  Thanks for the heads up. Yes, it can be removed. I've just cut a new release replacing syslog with logging.  Let me know how you get on.

**Comment by awbacker** [comment]
Great.  I was going to suggest logging as well.  We use remote syslog through that.

**Comment by Jelle7** [comment]
Issue is resolved. Thank you
