### ISSUE TITLE
How to install this package in docker

### ISSUE THREAD

**Issue by mindnuts** [HandsetDetection/python-apikit#20]
Hi..i am trying to dockerize the handset API. Not able to figure out how to install this package inside the container.

Do i need to:

``` bash
pip install https://github.com/HandsetDetection/python-apikit/archive/master.zip
```

**Comment by elricho** [comment]
Hey @mindnuts, That command looks fine. Is it producing an error ?

**Comment by mindnuts** [comment]
@elricho Well it just downloads the source files from Github. It does not install the dependencies of this project. Am i supposed to install them manually?

**Comment by elricho** [comment]
Right - I see the issue.  I think when you pip install from the repo the requirements.txt does not get read so yes, you'll need to either install them manually first or clone the repo, install the requirements.txt then install the package.

This URL covers the two approaches. https://github.com/pypa/pip/issues/3610

**Comment by mindnuts** [comment]
@elricho Thanks...i ended up intalling the dependencies manually.
